# Generated by Django 2.2.5 on 2021-07-14 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=140)),
                ('description', models.TextField()),
                ('disease1', models.CharField(choices=[('no_finding', 'no_finding'), ('atelectasis', 'atelectasis'), ('cardiomegaly', 'cardiomegaly'), ('consolidation', 'consolidation'), ('edema', 'edema'), ('effusion', 'effusion'), ('emphysema', 'emphysema'), ('fibrosis', 'fibrosis'), ('hernia', 'hernia'), ('infiltration', 'infiltration'), ('mass', 'mass'), ('nodule', 'nodule'), ('pleural_thickening', 'pleural_thickening'), ('pneumonia', 'pneumonia'), ('pneumothorax', 'pneumothorax')], default='no_finding', max_length=20)),
                ('disease2', models.CharField(choices=[('no_finding', 'no_finding'), ('atelectasis', 'atelectasis'), ('cardiomegaly', 'cardiomegaly'), ('consolidation', 'consolidation'), ('edema', 'edema'), ('effusion', 'effusion'), ('emphysema', 'emphysema'), ('fibrosis', 'fibrosis'), ('hernia', 'hernia'), ('infiltration', 'infiltration'), ('mass', 'mass'), ('nodule', 'nodule'), ('pleural_thickening', 'pleural_thickening'), ('pneumonia', 'pneumonia'), ('pneumothorax', 'pneumothorax')], default='no_finding', max_length=20)),
                ('disease3', models.CharField(choices=[('no_finding', 'no_finding'), ('atelectasis', 'atelectasis'), ('cardiomegaly', 'cardiomegaly'), ('consolidation', 'consolidation'), ('edema', 'edema'), ('effusion', 'effusion'), ('emphysema', 'emphysema'), ('fibrosis', 'fibrosis'), ('hernia', 'hernia'), ('infiltration', 'infiltration'), ('mass', 'mass'), ('nodule', 'nodule'), ('pleural_thickening', 'pleural_thickening'), ('pneumonia', 'pneumonia'), ('pneumothorax', 'pneumothorax')], default='no_finding', max_length=20)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars')),
                ('age', models.IntegerField()),
                ('seriousness', models.CharField(choices=[('low', 'low'), ('middle', 'middle'), ('high', 'high')], default='low', max_length=10)),
                ('gender', models.CharField(choices=[('female', 'female'), ('male', 'male')], default='female', max_length=10)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
