# Generated by Django 3.2.9 on 2021-12-02 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('file', models.ImageField(blank=True, null=True, upload_to='patient_images')),
                ('detection_file', models.ImageField(blank=True, null=True, upload_to='patient_detect_images/exp')),
                ('disease1', models.CharField(blank=True, choices=[('no_finding', 'no_finding'), ('atelectasis', 'atelectasis'), ('cardiomegaly', 'cardiomegaly'), ('consolidation', 'consolidation'), ('edema', 'edema'), ('effusion', 'effusion'), ('emphysema', 'emphysema'), ('fibrosis', 'fibrosis'), ('hernia', 'hernia'), ('infiltration', 'infiltration'), ('mass', 'mass'), ('nodule', 'nodule'), ('pleural_thickening', 'pleural_thickening'), ('pneumonia', 'pneumonia'), ('pneumothorax', 'pneumothorax')], default='no_finding', max_length=20)),
                ('disease2', models.CharField(blank=True, choices=[('no_finding', 'no_finding'), ('atelectasis', 'atelectasis'), ('cardiomegaly', 'cardiomegaly'), ('consolidation', 'consolidation'), ('edema', 'edema'), ('effusion', 'effusion'), ('emphysema', 'emphysema'), ('fibrosis', 'fibrosis'), ('hernia', 'hernia'), ('infiltration', 'infiltration'), ('mass', 'mass'), ('nodule', 'nodule'), ('pleural_thickening', 'pleural_thickening'), ('pneumonia', 'pneumonia'), ('pneumothorax', 'pneumothorax')], default='no_finding', max_length=20)),
                ('disease3', models.CharField(blank=True, choices=[('no_finding', 'no_finding'), ('atelectasis', 'atelectasis'), ('cardiomegaly', 'cardiomegaly'), ('consolidation', 'consolidation'), ('edema', 'edema'), ('effusion', 'effusion'), ('emphysema', 'emphysema'), ('fibrosis', 'fibrosis'), ('hernia', 'hernia'), ('infiltration', 'infiltration'), ('mass', 'mass'), ('nodule', 'nodule'), ('pleural_thickening', 'pleural_thickening'), ('pneumonia', 'pneumonia'), ('pneumothorax', 'pneumothorax')], default='no_finding', max_length=20)),
                ('percentage1', models.IntegerField(default=50)),
                ('percentage2', models.IntegerField(default=50)),
                ('percentage3', models.IntegerField(default=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Diagnosis',
        ),
        migrations.AddField(
            model_name='patient',
            name='doctor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='patients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='image',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='patients.patient'),
        ),
    ]
