<<<<<<< HEAD:patients/migrations/0002_auto_20210731_0028.py
# Generated by Django 2.2.5 on 2021-07-30 15:28
=======
# Generated by Django 3.2.5 on 2021-07-25 12:17
>>>>>>> b070a8123d9ff46db9f1aff5a6cc5bccff5b659d:patients/migrations/0002_initial.py

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='patients.Patient'),
        ),
    ]
