# Generated by Django 3.2.5 on 2021-07-18 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='area',
        ),
        migrations.AlterField(
            model_name='patient',
            name='disease1',
            field=models.CharField(blank=True, choices=[('no_finding', 'no_finding'), ('atelectasis', 'atelectasis'), ('cardiomegaly', 'cardiomegaly'), ('consolidation', 'consolidation'), ('edema', 'edema'), ('effusion', 'effusion'), ('emphysema', 'emphysema'), ('fibrosis', 'fibrosis'), ('hernia', 'hernia'), ('infiltration', 'infiltration'), ('mass', 'mass'), ('nodule', 'nodule'), ('pleural_thickening', 'pleural_thickening'), ('pneumonia', 'pneumonia'), ('pneumothorax', 'pneumothorax')], default='no_finding', max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='disease2',
            field=models.CharField(blank=True, choices=[('no_finding', 'no_finding'), ('atelectasis', 'atelectasis'), ('cardiomegaly', 'cardiomegaly'), ('consolidation', 'consolidation'), ('edema', 'edema'), ('effusion', 'effusion'), ('emphysema', 'emphysema'), ('fibrosis', 'fibrosis'), ('hernia', 'hernia'), ('infiltration', 'infiltration'), ('mass', 'mass'), ('nodule', 'nodule'), ('pleural_thickening', 'pleural_thickening'), ('pneumonia', 'pneumonia'), ('pneumothorax', 'pneumothorax')], default='no_finding', max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='disease3',
            field=models.CharField(blank=True, choices=[('no_finding', 'no_finding'), ('atelectasis', 'atelectasis'), ('cardiomegaly', 'cardiomegaly'), ('consolidation', 'consolidation'), ('edema', 'edema'), ('effusion', 'effusion'), ('emphysema', 'emphysema'), ('fibrosis', 'fibrosis'), ('hernia', 'hernia'), ('infiltration', 'infiltration'), ('mass', 'mass'), ('nodule', 'nodule'), ('pleural_thickening', 'pleural_thickening'), ('pneumonia', 'pneumonia'), ('pneumothorax', 'pneumothorax')], default='no_finding', max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='seriousness',
            field=models.CharField(blank=True, choices=[('low', 'low'), ('middle', 'middle'), ('high', 'high')], default='low', max_length=10),
        ),
    ]
