# Generated by Django 2.2.5 on 2021-08-09 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_auto_20210808_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('file', models.ImageField(blank=True, null=True, upload_to='patient_images')),
                ('disease1', models.CharField(blank=True, choices=[('no_finding', 'no_finding'), ('atelectasis', 'atelectasis'), ('cardiomegaly', 'cardiomegaly'), ('consolidation', 'consolidation'), ('edema', 'edema'), ('effusion', 'effusion'), ('emphysema', 'emphysema'), ('fibrosis', 'fibrosis'), ('hernia', 'hernia'), ('infiltration', 'infiltration'), ('mass', 'mass'), ('nodule', 'nodule'), ('pleural_thickening', 'pleural_thickening'), ('pneumonia', 'pneumonia'), ('pneumothorax', 'pneumothorax')], default='no_finding', max_length=20)),
                ('disease2', models.CharField(blank=True, choices=[('no_finding', 'no_finding'), ('atelectasis', 'atelectasis'), ('cardiomegaly', 'cardiomegaly'), ('consolidation', 'consolidation'), ('edema', 'edema'), ('effusion', 'effusion'), ('emphysema', 'emphysema'), ('fibrosis', 'fibrosis'), ('hernia', 'hernia'), ('infiltration', 'infiltration'), ('mass', 'mass'), ('nodule', 'nodule'), ('pleural_thickening', 'pleural_thickening'), ('pneumonia', 'pneumonia'), ('pneumothorax', 'pneumothorax')], default='no_finding', max_length=20)),
                ('disease3', models.CharField(blank=True, choices=[('no_finding', 'no_finding'), ('atelectasis', 'atelectasis'), ('cardiomegaly', 'cardiomegaly'), ('consolidation', 'consolidation'), ('edema', 'edema'), ('effusion', 'effusion'), ('emphysema', 'emphysema'), ('fibrosis', 'fibrosis'), ('hernia', 'hernia'), ('infiltration', 'infiltration'), ('mass', 'mass'), ('nodule', 'nodule'), ('pleural_thickening', 'pleural_thickening'), ('pneumonia', 'pneumonia'), ('pneumothorax', 'pneumothorax')], default='no_finding', max_length=20)),
                ('percentage1', models.IntegerField(default=50)),
                ('percentage2', models.IntegerField(default=50)),
                ('percentage3', models.IntegerField(default=50)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='patients.Patient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Diagnosis',
        ),
    ]
