# Generated by Django 2.2.5 on 2021-07-14 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('area', models.CharField(choices=[('cpr', 'cpr'), ('critical_care_areas', 'critical_care_areas'), ('casualty_department ', 'casualty_department'), ('emergency_patient_areas', 'emergency_patient_areas')], default='casualty_department ', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='patient',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='disease1',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='disease2',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='disease3',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='seriousness',
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('file', models.ImageField(upload_to='patient_images')),
                ('disease1', models.CharField(choices=[('no_finding', 'no_finding'), ('atelectasis', 'atelectasis'), ('cardiomegaly', 'cardiomegaly'), ('consolidation', 'consolidation'), ('edema', 'edema'), ('effusion', 'effusion'), ('emphysema', 'emphysema'), ('fibrosis', 'fibrosis'), ('hernia', 'hernia'), ('infiltration', 'infiltration'), ('mass', 'mass'), ('nodule', 'nodule'), ('pleural_thickening', 'pleural_thickening'), ('pneumonia', 'pneumonia'), ('pneumothorax', 'pneumothorax')], default='no_finding', max_length=20)),
                ('disease2', models.CharField(choices=[('no_finding', 'no_finding'), ('atelectasis', 'atelectasis'), ('cardiomegaly', 'cardiomegaly'), ('consolidation', 'consolidation'), ('edema', 'edema'), ('effusion', 'effusion'), ('emphysema', 'emphysema'), ('fibrosis', 'fibrosis'), ('hernia', 'hernia'), ('infiltration', 'infiltration'), ('mass', 'mass'), ('nodule', 'nodule'), ('pleural_thickening', 'pleural_thickening'), ('pneumonia', 'pneumonia'), ('pneumothorax', 'pneumothorax')], default='no_finding', max_length=20)),
                ('disease3', models.CharField(choices=[('no_finding', 'no_finding'), ('atelectasis', 'atelectasis'), ('cardiomegaly', 'cardiomegaly'), ('consolidation', 'consolidation'), ('edema', 'edema'), ('effusion', 'effusion'), ('emphysema', 'emphysema'), ('fibrosis', 'fibrosis'), ('hernia', 'hernia'), ('infiltration', 'infiltration'), ('mass', 'mass'), ('nodule', 'nodule'), ('pleural_thickening', 'pleural_thickening'), ('pneumonia', 'pneumonia'), ('pneumothorax', 'pneumothorax')], default='no_finding', max_length=20)),
                ('seriousness', models.CharField(choices=[('low', 'low'), ('middle', 'middle'), ('high', 'high')], default='low', max_length=10)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='patients.Patient')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
