# Generated by Django 2.2.5 on 2021-07-22 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_auto_20210722_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='patient_images'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis', to='patients.Patient'),
        ),
    ]
