# Generated by Django 2.2.5 on 2021-09-07 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_auto_20210815_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='detection_file',
            field=models.ImageField(blank=True, null=True, upload_to='patient_detect_images/exp'),
        ),
    ]
