# Generated by Django 2.2.5 on 2021-07-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_auto_20210722_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='patients', to='patients.Diagnosis'),
        ),
    ]
