# Generated by Django 2.2.5 on 2021-07-22 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_patient_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='images',
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='patients.Patient'),
        ),
    ]
